name: Frontend CD

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'k8s/frontend.yaml'
      - '.github/workflows/reusable-cd.yml'
  workflow_dispatch:

jobs:
  call-reusable-cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      service: frontend
      aks_cluster_name: ${{ secrets.AKS_CLUSTER }}
      aks_resource_group: ${{ secrets.AKS_RG }}
      aks_acr_name: ${{ secrets.ACR_NAME }}
    secrets: inherit