name: Frontend CI

on:
  pull_request:
    branches: [development]
    paths:
      - 'frontend/**'
      - '.github/workflows/reusable-ci.yml'
  push:
    branches: [development]
    paths:
      - 'frontend/**'
      - '.github/workflows/reusable-ci.yml'
  workflow_dispatch:

jobs:
  call-reusable-ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      service_path: frontend